# Generated by Django 3.2.16 on 2023-01-18 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("sku", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("called", models.IntegerField(default=0)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.brand"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
